# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-24 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_auto_20160818_1058'),
        ('user_profiles', '0002_auto_20160819_0428'),
    ]

    operations = [
    ]
