# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-09 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0004_auto_20160831_0631'),
        ('user_profiles', '0004_userprofile_training_kits_seen'),
    ]

    operations = [
    ]
