# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-03 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
        ('user_profiles', '0006_auto_20160914_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage', to='stages.Stage'),
        ),
    ]
