# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-04 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0007_userprofile_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
