# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-15 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0008_userprofile_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='number_of_missed_calls',
            field=models.IntegerField(default=0),
        ),
    ]
