# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-19 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0001_initial'),
        ('user_profiles', '0010_auto_20161015_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='guild',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='guilds.Guild'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='stages.Stage'),
        ),
    ]
