# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-23 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0013_auto_20161125_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[(b'HL', b'Helpline'), (b'VL', b'Volunteer'), (b'AD', b'Admin'), (b'BN', b'Beneficiary')], default=b'BN', max_length=2),
        ),
    ]
