# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-28 03:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profiles', '0014_auto_20161223_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[(b'HL', b'Helpline'), (b'VL', b'Volunteer'), (b'AD', b'Admin'), (b'BN', b'Beneficiary'), (b'SS', b'ShikshaSahyogi'), (b'SSCoach', b'ShikshaSahyogiCoach')], default=b'BN', max_length=2),
        ),
    ]
