# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-16 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0015_auto_20171128_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[(b'HL', b'Helpline'), (b'VL', b'Volunteer'), (b'AD', b'Admin'), (b'BN', b'Beneficiary'), (b'SS', b'ShikshaSahyogi'), (b'SSCoach', b'ShikshaSahyogiCoach')], default=b'BN', max_length=10),
        ),
    ]
