# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-01 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0002_auto_20160901_0544'),
        ('stages', '0001_initial'),
        ('task_status', '0003_taskstatus_category'),
        ('task_types', '0005_tasktype_form'),
        ('hooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_tags', models.ManyToManyField(blank=True, to='tags.Tag')),
                ('hooks', models.ManyToManyField(blank=True, to='hooks.Hook')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stages.Stage')),
                ('task_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task_status.TaskStatus')),
                ('task_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task_types.TaskType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
