# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-02 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hooks', '0002_auto_20161001_0922'),
        ('event_conditions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcondition',
            name='hooks',
        ),
        migrations.AddField(
            model_name='eventcondition',
            name='hook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hooks.Hook'),
        ),
        migrations.AddField(
            model_name='eventcondition',
            name='name',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
