# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-03 09:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_conditions', '0002_auto_20161002_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcondition',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
