# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-03 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_conditions', '0003_eventcondition_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcondition',
            name='event_condition_type',
            field=models.CharField(choices=[(b'USER', b'User'), (b'TASK', b'Task')], default=b'USER', max_length=4),
        ),
    ]
