# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-25 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_auto_20161024_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='name',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='space',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
