# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-25 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_types', '0001_initial'),
        ('spaces', '0004_auto_20161025_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='space_type',
        ),
        migrations.AddField(
            model_name='space',
            name='space_type',
            field=models.ManyToManyField(blank=True, related_name='spaces', to='space_types.SpaceType'),
        ),
    ]
