# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-14 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_types', '0007_tasktype_sla'),
        ('event_conditions', '0005_eventcondition_event_condition_category'),
        ('task_status', '0003_taskstatus_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_event_conditions', models.ManyToManyField(blank=True, related_name='exotel', to='event_conditions.EventCondition')),
                ('default_task_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_status.TaskStatus')),
                ('default_task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_types.TaskType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
