# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-14 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exotel',
            name='default_task_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task_status.TaskStatus'),
        ),
        migrations.AlterField(
            model_name='exotel',
            name='default_task_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task_types.TaskType'),
        ),
    ]
