# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-22 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
        ('exotel', '0002_auto_20161014_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='exotel',
            name='default_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stages.Stage'),
        ),
    ]
