# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-22 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exotel', '0003_exotel_default_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='exotel',
            name='auto_assign',
            field=models.BooleanField(default=False),
        ),
    ]
