# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-03 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20161001_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='hook',
        ),
    ]
