# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-05 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pledge',
            unique_together=set([('task', 'user')]),
        ),
    ]
