# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-09 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0002_auto_20170105_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
