# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-09 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0003_pledge_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
