# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-02 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('child', '0001_initial'),
        ('worker', '0001_initial'),
        ('kits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(default='', max_length=20)),
                ('date', models.DateField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_child', to='child.Child')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_kit', to='kits.IAKit')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_worker', to='worker.Worker')),
            ],
        ),
    ]
