# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-27 04:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20160729_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='estimation',
        ),
        migrations.RemoveField(
            model_name='task',
            name='feedback_type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='points',
        ),
    ]
