# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-15 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20160915_0546'),
        ('tasks', '0003_auto_20160827_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='form_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='forms.FormData'),
        ),
    ]
