# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-22 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_form_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignee_rating',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='beneficiary_rating',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
