# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-26 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20161004_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignee_rating',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
