# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-05 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20161226_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
