# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-05 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0001_initial'),
        ('tasks', '0008_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='interests',
            field=models.ManyToManyField(null=True, related_name='tasks', to='interests.Interest'),
        ),
    ]
