# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-05 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20160915_0713'),
        ('tasks', '0010_auto_20170105_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='locations.Location'),
        ),
    ]
