# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-05 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_task_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='interests',
            new_name='task_interests',
        ),
    ]
