# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-07 04:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0012_auto_20170105_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='party',
            field=models.ManyToManyField(blank=True, related_name='group_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
