# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-16 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_task_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_interests',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='interests.Interest'),
        ),
    ]
