# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-18 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_auto_20170216_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='mobile',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
