# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-02 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0005_location_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('mobile', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_locations', to='locations.Location')),
            ],
        ),
    ]
