# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-02 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='worker',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='parent_worker', to='worker.Worker'),
            preserve_default=False,
        ),
    ]
