# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-13 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_status_categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatuscategory',
            name='task_completed_flag',
            field=models.BooleanField(default=False),
        ),
    ]
