# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-15 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_status_categories', '0002_taskstatuscategory_task_completed_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatuscategory',
            name='task_completed_flag',
            field=models.CharField(choices=[(b'TODO', b'To Do'), (b'PROG', b'In Progress'), (b'DONE', b'Done')], default=b'TODO', max_length=4),
        ),
    ]
