# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-24 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_types', '0002_tasktype_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('desc', models.TextField(blank=True)),
                ('create_task_on_transition', models.BooleanField(default=False)),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='task_types.TaskType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
