# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-17 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IAUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
            ],
        ),
    ]
