# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-17 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodels', '0002_auto_20170917_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, null=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='dbmodels.Assessment')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='center_address', to='dbmodels.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('dateOfBirth', models.DateField(null=True)),
                ('age', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='IAParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_address', to='dbmodels.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('max_marks', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, null=True)),
                ('amount', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='iauser',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_address', to='dbmodels.Address'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='iaUser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmodels.IAUser'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='kit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmodels.Kit'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='parent',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmodels.IAParent'),
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbmodels.IAParent'),
        ),
        migrations.AddField(
            model_name='center',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='dbmodels.IAUser'),
        ),
        migrations.AddField(
            model_name='assessmentscore',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='dbmodels.Question'),
        ),
        migrations.AddField(
            model_name='assessmentscore',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbmodels.AssessmentReport'),
        ),
        migrations.AddField(
            model_name='assessmentreport',
            name='child',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='dbmodels.Child'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='kits',
            field=models.ManyToManyField(to='dbmodels.Kit'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='questions',
            field=models.ManyToManyField(to='dbmodels.Question'),
        ),
    ]
