# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-16 09:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message_templates', '0002_auto_20160916_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
