# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-14 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='pincode',
            new_name='postal_code',
        ),
    ]
