# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-14 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20160914_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=models.CharField(default=b'', max_length=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='street_number',
            field=models.CharField(default=b'', max_length=10),
        ),
    ]
