# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-14 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20160914_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
    ]
