# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-15 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_location_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='administrative_area_level_1',
            field=models.CharField(blank=True, default=b'', max_length=40),
        ),
        migrations.AlterField(
            model_name='location',
            name='administrative_area_level_2',
            field=models.CharField(blank=True, default=b'', max_length=40),
        ),
        migrations.AlterField(
            model_name='location',
            name='locality',
            field=models.CharField(blank=True, default=b'', max_length=40),
        ),
        migrations.AlterField(
            model_name='location',
            name='sublocality_level_1',
            field=models.CharField(blank=True, default=b'', max_length=40),
        ),
        migrations.AlterField(
            model_name='location',
            name='sublocality_level_2',
            field=models.CharField(blank=True, default=b'', max_length=40),
        ),
        migrations.AlterField(
            model_name='location',
            name='sublocality_level_3',
            field=models.CharField(blank=True, default=b'', max_length=40),
        ),
    ]
