# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-02 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
