# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-09 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('child', '0001_initial'),
        ('questions', '0001_initial'),
        ('worker', '0001_initial'),
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(default='', max_length=255)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_assessment_item', to='assessments.Assessment')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_child_item', to='child.Child')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_item', to='questions.Question')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_worker_item', to='worker.Worker')),
            ],
        ),
    ]
