# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-02 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='desc',
            field=models.TextField(max_length=100),
        ),
    ]
