# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-22 07:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0005_auto_20160922_0703'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('end', models.BooleanField(default=False)),
                ('beneficiary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_calls', to=settings.AUTH_USER_MODEL)),
                ('caller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caller_calls', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
