# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-14 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_kits', '0002_page_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingkit',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
