# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-27 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_kits', '0003_auto_20160914_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
