# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-17 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodels', '0003_auto_20170917_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='iauser',
            name='hashValue',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
