# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-16 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message_templates', '0001_initial'),
        ('user_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='message_templates.MessageTemplate'),
        ),
    ]
