# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-12 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivrs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivr',
            name='exotel_app_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ivr',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
