# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-09 08:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ivrs', '0003_auto_20161014_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivr',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ivrs_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
