# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-09 11:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='New Form', max_length=20)),
                ('description', models.CharField(default='Description', max_length=100)),
                ('schema', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='forms.Form')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
