# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-27 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20160915_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentForm',
            fields=[
                ('form_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms.Form')),
                ('peristent', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('forms.form',),
        ),
    ]
