# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-27 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_persistentform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persistentform',
            old_name='peristent',
            new_name='persistent',
        ),
    ]
