# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-26 07:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0005_persistentformdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='beneficiary_form',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_beneficiary', to=settings.AUTH_USER_MODEL),
        ),
    ]
