# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-18 09:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_formdata_beneficiary_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='beneficiary_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_beneficiary', to=settings.AUTH_USER_MODEL),
        ),
    ]
