# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-01 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hook_type', models.CharField(choices=[(b'SM', b'Send Message'), (b'CT', b'CreateTask'), (b'SI', b'Send IVR'), (b'AT', b'Add Tag'), (b'CS', b'Change Stage')], default=b'SM', max_length=2)),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hook', to='actions.Action')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
