# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-04 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hooks', '0003_auto_20161003_0700'),
        ('hooks', '0003_auto_20161003_0917'),
    ]

    operations = [
    ]
