# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-10 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hooks', '0004_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hook',
            name='hook_type',
            field=models.CharField(choices=[(b'SM', b'Send Message'), (b'CT', b'Create Task'), (b'SI', b'Send IVR'), (b'AT', b'Add Tag'), (b'CS', b'Change Stage'), (b'AU', b'Archive User')], default=b'SM', max_length=2),
        ),
    ]
