# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-08 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_name', models.CharField(default='', max_length=20)),
                ('assessment_description', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
