# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-27 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_types', '0002_feedbacktype_desc'),
        ('task_types', '0002_tasktype_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='estimation',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='feedback_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_types', to='feedback_types.FeedbackType'),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
