# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-14 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_kits', '0003_auto_20160914_0722'),
        ('task_types', '0003_auto_20160827_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='training_kit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_types', to='training_kits.TrainingKit'),
        ),
    ]
