# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-04 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_status', '0003_taskstatus_category'),
        ('task_types', '0005_tasktype_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='default_task_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_types', to='task_status.TaskStatus'),
        ),
    ]
