# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-10 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_types', '0006_tasktype_default_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='sla',
            field=models.IntegerField(default=24),
        ),
    ]
